# Generated by Django 3.2.5 on 2021-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=5)),
            ],
        ),
    ]
